import Head from 'next/head';
import Link from 'src/components/link';
import { Center, Box, Heading, Text } from '@chakra-ui/react';
export default function Home() {
  return (
    <div>
      <Head>
        <title>We are Kost!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center p={12}>
        <Box bg="secondary.400" w={'lg'} rounded="lg" shadow="lg" p={12}>
          <Heading as="h1" color={'white'} size="lg">
            Kost Home Page!
          </Heading>
          <Box mt={2}>
            <Text>Pages Working On:</Text>
            <Link to="/login">Login</Link>
          </Box>
        </Box>
      </Center>
    </div>
  );
}
