import Head from 'next/head';
import Link from 'src/components/link';
import { Center, Box, Button, HStack, Heading, Text, useToast } from '@chakra-ui/react';
import { useAuthStore } from 'src/store';
import { logout } from 'src/requests/auth';
import Navbar from 'src/components/navbar';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Kost App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Center p={12}>
        <Box bg="secondary.400" w={'lg'} rounded="lg" shadow="lg" p={12}>
          <Heading as="h1" color={'white'} size="lg">
            Kost Home Page!
          </Heading>
        </Box>
      </Center>
    </div>
  );
}
