import Head from 'next/head';
import Link from 'src/components/link';
import { Center, Box, Button, HStack, Heading, Text, useToast } from '@chakra-ui/react';
import { useAuthStore } from 'src/store';
import { logout } from 'src/requests/auth';
export default function Home() {
  const toast = useToast();
  const user = useAuthStore((s) => s.user);

  const handleLogout = async () => {
    const res = await logout();
    if (res) {
      return toast({
        title: 'You have been logged out.',
        description: "We've created your account for you.",
        status: 'success',
        duration: 3000,
        isClosable: true,
      });
    }
    toast({
      title: 'Oops.',
      description: "We've encountered an error.",
      status: 'error',
      duration: 3000,
      isClosable: false,
    });
  };

  return (
    <div>
      <Head>
        <title>We are Kost!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center p={12}>
        <Box bg="secondary.400" w={'lg'} rounded="lg" shadow="lg" p={12}>
          <Heading as="h1" color={'white'} size="lg">
            Kost Home Page!
          </Heading>
          <Box my={2}>
            {user ? (
              <HStack>
                <Text>
                  You are logged in as {user.firstName} {user.lastName}
                </Text>
                <Button onClick={handleLogout} variant="ghost">
                  Log out
                </Button>
              </HStack>
            ) : (
              <Text> You are not logged in </Text>
            )}
          </Box>
          <Box mt={2}>
            <Text>Pages Working On:</Text>
            <ol>
              <li>
                <Link to="/login">Login</Link>
              </li>
              <li>
                <Link to="/signup">Signup</Link>
              </li>
            </ol>
          </Box>
        </Box>
      </Center>
    </div>
  );
}
